#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class Event:
    kind: str
    args: list[int]


def parse_script(text: str) -> dict[int, list[Event]]:
    events: dict[int, list[Event]] = {}
    frame = 0
    for raw in text.splitlines():
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        parts = line.split()
        cmd = parts[0]
        if cmd == "wait" or cmd == "frames":
            if len(parts) != 2:
                raise ValueError(f"invalid {cmd}: {raw}")
            frame += int(parts[1])
            continue
        if cmd in ("click", "pointer"):
            if len(parts) != 3:
                raise ValueError(f"invalid {cmd}: {raw}")
            x = int(float(parts[1]))
            y = int(float(parts[2]))
            events.setdefault(frame, []).append(Event(cmd, [x, y]))
            continue
        if cmd == "scroll":
            if len(parts) != 3:
                raise ValueError(f"invalid {cmd}: {raw}")
            dx = int(float(parts[1]))
            dy = int(float(parts[2]))
            events.setdefault(frame, []).append(Event(cmd, [dx, dy]))
            continue
        if cmd == "snapshot":
            events.setdefault(frame, []).append(Event(cmd, []))
            continue
        raise ValueError(f"unknown command: {cmd} ({raw})")
    return events


WEB_VISUAL_JS = r"""// Auto-generated by tests/visual/gen_web_visual_js.py
(function () {
  function parseQuery() {
    try {
      return new URLSearchParams(location.search);
    } catch (e) {
      return new URLSearchParams();
    }
  }

  function dispatchMouse(type, x, y, button) {
    const el = document.elementFromPoint(x, y) || document.body;
    const ev = new MouseEvent(type, {
      bubbles: true,
      cancelable: true,
      clientX: x,
      clientY: y,
      button: button ?? 0,
      buttons: type === "mousemove" ? 0 : 1,
    });
    el.dispatchEvent(ev);
  }

  function dispatchWheel(x, y, dx, dy) {
    // Note: Synthetic WheelEvent does NOT trigger browser default scrolling.
    // For COI visual tests we need deterministic scroll, so we scroll the nearest
    // scrollable container directly and also dispatch a wheel event for listeners.
    let el = document.elementFromPoint(x, y) || document.body;

    function isScrollableAxis(node, axis) {
      if (!node || node === document.documentElement) return true;
      const cs = window.getComputedStyle(node);
      if (!cs) return false;
      if (axis === "x") {
        if (!(cs.overflowX === "auto" || cs.overflowX === "scroll")) return false;
        return node.scrollWidth > node.clientWidth;
      }
      if (!(cs.overflowY === "auto" || cs.overflowY === "scroll")) return false;
      return node.scrollHeight > node.clientHeight;
    }

    function findScrollable(node, dx0, dy0) {
      let cur = node;
      while (cur && cur !== document.body && cur !== document.documentElement) {
        const okX = dx0 !== 0 && isScrollableAxis(cur, "x");
        const okY = dy0 !== 0 && isScrollableAxis(cur, "y");
        if (okX || okY) return cur;
        cur = cur.parentElement;
      }
      return document.scrollingElement || document.documentElement;
    }

    const target = findScrollable(el, dx, dy);
    if (target) {
      if (dx) target.scrollLeft += dx;
      if (dy) target.scrollTop += dy;
    }

    const ev = new WheelEvent("wheel", {
      bubbles: true,
      cancelable: true,
      clientX: x,
      clientY: y,
      deltaX: dx,
      deltaY: dy,
    });
    el.dispatchEvent(ev);
  }

  const q = parseQuery();
  if (!q.has("coi_visual")) return;

  const captureIndex = parseInt(q.get("coi_visual_capture_index") || "0", 10) || 0;
  const captureEvery = Math.max(1, parseInt(q.get("coi_visual_every") || "60", 10) || 60);

  const eventsByFrame = __COI_VISUAL_EVENTS__;
  const maxFrame = __COI_VISUAL_MAX_FRAME__;
  window.__coi_visual_capture_index = captureIndex;
  window.__coi_visual_capture_every = captureEvery;
  window.__coi_visual_max_frame = maxFrame;
  window.__coi_visual_done = false;

  let pointerX = 0;
  let pointerY = 0;

  function runFrame(frame) {
    const evs = eventsByFrame[String(frame)];
    if (!evs) return;
    for (const ev of evs) {
      const kind = ev[0];
      const args = ev[1];
      if (kind === "pointer") {
        pointerX = args[0];
        pointerY = args[1];
        dispatchMouse("mousemove", pointerX, pointerY);
      } else if (kind === "click") {
        pointerX = args[0];
        pointerY = args[1];
        dispatchMouse("mousemove", pointerX, pointerY);
        dispatchMouse("mousedown", pointerX, pointerY, 0);
        dispatchMouse("mouseup", pointerX, pointerY, 0);
        dispatchMouse("click", pointerX, pointerY, 0);
      } else if (kind === "scroll") {
        dispatchWheel(pointerX, pointerY, args[0], args[1]);
      }
    }
  }

  // Capture index semantics (approximate native runner):
  // - 0: baseline (no scripted input applied), but wait for the app to mount.
  // - 1+: advance a simulated frame counter until at least:
  //     - captureIndex * captureEvery (native capture-every), and
  //     - the last scripted event frame (maxFrame)
  //
  // We dispatch script events on those simulated frames (rAF-based).

  function hasNonScriptBodyChild() {
    const kids = document.body ? document.body.children : [];
    for (const el of kids) {
      if (el && el.tagName && el.tagName.toUpperCase() !== "SCRIPT") return true;
    }
    return false;
  }

  function raf(n, fn) {
    if (n <= 0) return fn();
    requestAnimationFrame(() => raf(n - 1, fn));
  }

  function waitForAppMount(timeoutMs, done) {
    const start = (typeof performance !== "undefined" && performance.now) ? performance.now() : Date.now();
    function check() {
      // Optional handshake hook (apps may set this in the future).
      if (window.__coi_visual_ready === true) return done();

      // Most COI scenes render a `.root` node via WebCC DOM.
      if (document.querySelector(".root")) return done();

      // Fallback: anything besides our <script> tags means the app started committing DOM.
      if (hasNonScriptBodyChild()) return done();

      const now = (typeof performance !== "undefined" && performance.now) ? performance.now() : Date.now();
      if ((now - start) >= timeoutMs) return done();

      requestAnimationFrame(check);
    }
    requestAnimationFrame(check);
  }

  // Give the app a couple frames to mount before we start dispatching events,
  // then wait for a first DOM commit (or timeout).
  function start() {
    window.__coi_visual_started = true;
    raf(2, () => {
      waitForAppMount(2000, () => {
        // Baseline capture: just ensure the app has mounted and had a paint.
        if (captureIndex <= 0) {
          raf(2, () => {
            window.__coi_visual_done = true;
          });
          return;
        }

        // Scripted capture: run a rAF-driven “frame” loop to apply events and wait.
        // Note: We wait until captureIndex*captureEvery to better match native's capture timing.
        const targetFrame = Math.max(captureIndex * captureEvery, maxFrame);
        let frame = 0;
        function tick() {
          if (frame <= maxFrame) runFrame(frame);
          frame++;
          if (frame <= targetFrame) {
            requestAnimationFrame(tick);
          } else {
            // Give the COI/WebCC main loop a couple frames to consume the event buffer
            // and flush DOM changes before capture.
            raf(2, () => {
              window.__coi_visual_done = true;
            });
          }
        }
        requestAnimationFrame(tick);
      });
    });
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", start, { once: true });
  } else {
    start();
  }
})();
"""


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--script", type=Path, required=True)
    ap.add_argument("--out", type=Path, required=True)
    args = ap.parse_args()

    text = args.script.read_text(encoding="utf-8")
    events = parse_script(text)
    max_frame = max(events.keys(), default=0)
    if "wait" in text or "frames" in text:
        # Conservative: if script advances frames via waits, max_frame is already final frame.
        pass

    # Convert to JSON-friendly dict
    out_events: dict[str, list[list[object]]] = {}
    for f, evs in events.items():
        out_events[str(f)] = [[e.kind, e.args] for e in evs if e.kind != "snapshot"]

    js = WEB_VISUAL_JS.replace("__COI_VISUAL_EVENTS__", json.dumps(out_events, separators=(",", ":")))
    js = js.replace("__COI_VISUAL_MAX_FRAME__", str(max_frame))

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(js, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
