#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class Event:
    kind: str
    args: list[int]


def parse_script(text: str) -> dict[int, list[Event]]:
    events: dict[int, list[Event]] = {}
    frame = 0
    for raw in text.splitlines():
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        parts = line.split()
        cmd = parts[0]
        if cmd == "wait" or cmd == "frames":
            if len(parts) != 2:
                raise ValueError(f"invalid {cmd}: {raw}")
            frame += int(parts[1])
            continue
        if cmd in ("click", "pointer"):
            if len(parts) != 3:
                raise ValueError(f"invalid {cmd}: {raw}")
            x = int(float(parts[1]))
            y = int(float(parts[2]))
            events.setdefault(frame, []).append(Event(cmd, [x, y]))
            continue
        if cmd == "scroll":
            if len(parts) != 3:
                raise ValueError(f"invalid {cmd}: {raw}")
            dx = int(float(parts[1]))
            dy = int(float(parts[2]))
            events.setdefault(frame, []).append(Event(cmd, [dx, dy]))
            continue
        if cmd == "snapshot":
            events.setdefault(frame, []).append(Event(cmd, []))
            continue
        raise ValueError(f"unknown command: {cmd} ({raw})")
    return events


WEB_VISUAL_JS = r"""// Auto-generated by tests/visual/gen_web_visual_js.py
(function () {
  function parseQuery() {
    try {
      return new URLSearchParams(location.search);
    } catch (e) {
      return new URLSearchParams();
    }
  }

  function dispatchMouse(type, x, y, button) {
    const el = document.elementFromPoint(x, y) || document.body;
    const ev = new MouseEvent(type, {
      bubbles: true,
      cancelable: true,
      clientX: x,
      clientY: y,
      button: button ?? 0,
      buttons: type === "mousemove" ? 0 : 1,
    });
    el.dispatchEvent(ev);
  }

  function dispatchWheel(x, y, dx, dy) {
    const el = document.elementFromPoint(x, y) || document.body;
    const ev = new WheelEvent("wheel", {
      bubbles: true,
      cancelable: true,
      clientX: x,
      clientY: y,
      deltaX: dx,
      deltaY: dy,
    });
    el.dispatchEvent(ev);
  }

  const q = parseQuery();
  if (!q.has("coi_visual")) return;

  const captureIndex = parseInt(q.get("coi_visual_capture_index") || "0", 10) || 0;

  const eventsByFrame = __COI_VISUAL_EVENTS__;
  const maxFrame = __COI_VISUAL_MAX_FRAME__;

  let pointerX = 0;
  let pointerY = 0;

  function runFrame(frame) {
    const evs = eventsByFrame[String(frame)];
    if (!evs) return;
    for (const ev of evs) {
      const kind = ev[0];
      const args = ev[1];
      if (kind === "pointer") {
        pointerX = args[0];
        pointerY = args[1];
        dispatchMouse("mousemove", pointerX, pointerY);
      } else if (kind === "click") {
        pointerX = args[0];
        pointerY = args[1];
        dispatchMouse("mousemove", pointerX, pointerY);
        dispatchMouse("mousedown", pointerX, pointerY, 0);
        dispatchMouse("mouseup", pointerX, pointerY, 0);
        dispatchMouse("click", pointerX, pointerY, 0);
      } else if (kind === "scroll") {
        dispatchWheel(pointerX, pointerY, args[0], args[1]);
      }
    }
  }

  // Capture index semantics:
  // - 0: baseline (no scripted input applied)
  // - 1+: apply script up to the end
  if (captureIndex <= 0) return;

  // Execute scripted events in a rAF-driven “frame” loop.
  // This matches the desktop runner semantics well enough for initial web baselines.
  let frame = 0;
  function tick() {
    runFrame(frame);
    frame++;
    if (frame <= maxFrame) {
      requestAnimationFrame(tick);
    }
  }

  requestAnimationFrame(tick);
})();
"""


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--script", type=Path, required=True)
    ap.add_argument("--out", type=Path, required=True)
    args = ap.parse_args()

    text = args.script.read_text(encoding="utf-8")
    events = parse_script(text)
    max_frame = max(events.keys(), default=0)
    if "wait" in text or "frames" in text:
        # Conservative: if script advances frames via waits, max_frame is already final frame.
        pass

    # Convert to JSON-friendly dict
    out_events: dict[str, list[list[object]]] = {}
    for f, evs in events.items():
        out_events[str(f)] = [[e.kind, e.args] for e in evs if e.kind != "snapshot"]

    js = WEB_VISUAL_JS.replace("__COI_VISUAL_EVENTS__", json.dumps(out_events, separators=(",", ":")))
    js = js.replace("__COI_VISUAL_MAX_FRAME__", str(max_frame))

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(js, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

